// Package models contains the GORM models persisted by the application.
package models

import "time"

const (
	// MessageRoleUser identifies a message received from a Telegram user.
	MessageRoleUser = "user"
	// MessageRoleAssistant identifies a response generated by the assistant.
	MessageRoleAssistant = "assistant"
	// MessageRoleTool identifies the persisted output of one tool call.
	MessageRoleTool = "tool"
	// MessageRoleReasoning identifies encrypted provider reasoning state required
	// to continue a stateless Responses API tool call.
	MessageRoleReasoning = "reasoning"
)

// Message is one persisted conversation message. A conversation is identified by
// the Telegram chat and message thread; non-forum chats use a thread ID of zero.
type Message struct {
	ID              uint64 `gorm:"primaryKey"`
	ChatID          int64  `gorm:"not null;index:messages_conversation_created_at_index,priority:1"`
	MessageThreadID int    `gorm:"not null;default:0;index:messages_conversation_created_at_index,priority:2"`
	UserID          *int64
	Role            string `gorm:"not null"`
	Content         string `gorm:"not null"`
	ToolCallID      *string
	ToolName        *string
	ToolArguments   *string   `gorm:"type:jsonb"`
	CreatedAt       time.Time `gorm:"not null"`
}

// TableName returns the database table name used for persisted messages.
func (Message) TableName() string {
	return "messages"
}
