#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_file="${repository_root}/docs/code-index.md"
temporary_file="$(mktemp)"

cleanup_temporary_file() {
  rm -f "${temporary_file}"
}

trap cleanup_temporary_file EXIT

{
  cat <<'EOF'
---
title: Documentation Code Index
description: Generated index of the metadata declared by the project's documentation files.
methods: []
depends_on:
  - scripts/generate-code-index.sh
used_by: []
---

# Documentation Code Index

Generated with `scripts/generate-code-index.sh`. Do not edit this file manually.
EOF

  for documentation_file in "${repository_root}"/docs/*.md; do
    if [[ "${documentation_file}" == "${output_file}" ]]; then
      continue
    fi

    printf '\n## %s\n\n```yaml\n' "$(basename "${documentation_file}")"
    awk '
      NR == 1 {
        if ($0 != "---") {
          exit 1
        }
        in_front_matter = 1
        next
      }
      in_front_matter && $0 == "---" {
        exit
      }
      in_front_matter {
        print
      }
    ' "${documentation_file}"
    printf '```\n'
  done
} > "${temporary_file}"

mv "${temporary_file}" "${output_file}"
trap - EXIT
